=== RHM2001/PhotoTDS/PhotoTDS/xml/publicaciones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.tds.es/fotos" xmlns="http://www.tds.es/fotos"
    elementFormDefault="qualified">
    
    <xs:element name="publicaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="publicacion" type="Publicacion" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Publicacion">
        <xs:sequence>
            <xs:element name="usuario" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="descripcion" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="meGusta" type="xs:int" minOccurs="1" maxOccurs="1" />
            <xs:element name="hashtags" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="comentarios" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== RHM2001/PhotoTDS/PhotoTDS/xml/publicaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<publicaciones xmlns="http://www.tds.es/fotos" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://www.tds.es/fotos publicaciones.xsd">
    
    <publicacion>
        <usuario>raul</usuario>
        <descripcion>Prueba del cargador</descripcion>
        <meGusta>0</meGusta>
        <hashtags>prueba</hashtags>
        <file>C:\Users\Raul-\Pictures\Night Sky - frame at 0m1s.jpg</file>
        <comentarios>Prueba de comentarios</comentarios>
    </publicacion>

</publicaciones>
